# GitHub Sponsors configuration
# You can enable this later by uncommenting and adding your username

# github: rmn1978

# Other funding platforms (uncomment and add your usernames as needed)
# patreon: your-patreon
# ko_fi: your-kofi
# buy_me_a_coffee: your-username

custom:
  - https://twitter.com/learntouseai
